version: '3.1'

services:
  ent-pei-api:
    build:
      context: .
      dockerfile: DOCKERFILE
    restart: always
    ports:
      - 80:3000
      - 443:443
    volumes:
      - /home/lucien/ent-pei-api:/app
